### ISSUE TITLE
docker compose command deprecated 

### ISSUE THREAD

**Issue by danGitRys** [dgrewe-hse/golfClubPro#1]
Currently the used command for docker compose is **docker-compose**
In the new docker compose version the hypen can get removed
https://docs.docker.com/compose/releases/migrate/

**Comment by dgrewe-hse** [comment]
Hi @danGitRys,

thanks for open up the issue. Just to clarify, you are pointing to the given instructions in the README.md file, where the run instructions for docker compose need to be adjusted, right?

Best regards

**Comment by danGitRys** [comment]
Yes these commands can be addjusted in the README.md file 

**$ cd golfClubPro/docker-compose # go into the compose directory**
**$ docker-compose -f docker-compose.yml build    # builds you all the containers required**
**$ docker-compose -f docker-compose.yml up       # to start all containers in a composed environment | use "down" to stop the containers properly**

**Comment by dgrewe-hse** [comment]
Hi @danGitRys ,
I created a PR for the issue. Can you please provide a review?
BR;
